### ISSUE TITLE
Possible to add custom fields?

### ISSUE THREAD

**Issue by RafaelCENG** [markw65/fit-file-writer#3] opened 2024-08-20 09:03 UTC
First of all thanks for the package again. Can some custom fields be added for the fit file?
I tried to my extra fields in the fit-table.d.ts file and encode but apparently, it's not working. 
For example:
```
readonly variability_index: {
		readonly index: 255;
		readonly field: "variability_index";
		readonly type: "uint16";
		readonly scale: null;
		readonly offset: 0;
		readonly units: "";
};
```

**Comment by markw65** [comment] 2024-08-20 16:20
I'm not quite sure what you're trying to do. If you're saying there are some standard fields that are missing, I'd need to update [generate-fit-tables.ts](https://github.com/markw65/fit-file-writer/blob/main/tools/generate-fit-tables.ts) to include them.

If you're just trying to include what garmin calls custom fields in your FIT file, then the tests include an example of doing that:

First write the developer data id: https://github.com/markw65/fit-file-writer/blob/b5e285a71f503f8be3aaab522ee93aa7a360b0e8/test/test.ts#L113-L124

If you want the data to appear in Garmin's charts, the app-id has to be the id of a Garmin app which has been uploaded to the store, which defines the field in question. If you just want the data to be recorded, so that eg fit-file-reader can read it, the app-id can be anything. Note that it has to be specified as an array of 16 bytes, and the linked code does that by dropping the dashes, and then converting each pair of hex characters into its numeric equivalent.

If you have multiple fields from different apps, you need to create one developer id for each. The developer_ids are local to the file, so assign them as you like.

Then write the field definition: https://github.com/markw65/fit-file-writer/blob/b5e285a71f503f8be3aaab522ee93aa7a360b0e8/test/test.ts#L126-L138

Then in each record (where you want to include the custom data), create a `devInfo`, and pass it to writeMessage: https://github.com/markw65/fit-file-writer/blob/b5e285a71f503f8be3aaab522ee93aa7a360b0e8/test/test.ts#L178-L202

**Comment by RafaelCENG** [comment] 2024-08-20 20:58
You are a legend I will check it tomorrow and come back at it.  Thanks againYou are a legend I will check it tomorrow and come back at it.  Thanks again

**Comment by RafaelCENG** [comment] 2024-08-21 09:37
I managed to add the custom fields. I have multiple for my session and multiple for my records. For now I managed to show only one of them. Can't show simultaneous both.
```
		// Aeroscore Session
		const aeroscoreFieldNum = 0;
		fitWriter.writeMessage(
			"field_description",
			{
				developer_data_index: 0,
				field_definition_number: aeroscoreFieldNum,
				field_name: "aeroscore",
				fit_base_type_id: 137, // float64
			},
			null,
			true,
		);

		// Body Angle Record
		const bodyAngleFieldNum = 1;
		fitWriter.writeMessage(
			"field_description",
			{
				developer_data_index: 0,
				field_definition_number: bodyAngleFieldNum,
				field_name: "body_angle",
				fit_base_type_id: 137, // float64
				units: "degrees",
			},
			null,
			true,
		);
```
Should the developer_data_index be different for each one?

**Comment by RafaelCENG** [comment] 2024-08-21 13:28
Also sorry for the spam one more issue. When I console log my timestamps they look fine but on fit file viewer for some reason they are wrong
![image](https://github.com/user-attachments/assets/16b947bf-34b1-41ea-9ad6-85d432858955)
![image](https://github.com/user-attachments/assets/255e7339-445a-4d46-af8a-af5e673ea99f)
![image](https://github.com/user-attachments/assets/265d4a5e-f654-4bf2-9ed9-c630367f281f)

**Comment by markw65** [comment] 2024-08-21 15:46
> Should the developer_data_index be different for each one?

Only if the fields are generated by different apps.

My real code writes multiple custom fields, so it should work. Can you post how you construct the devInfo, and then write the "records"?

**Comment by markw65** [comment] 2024-08-21 15:49
For the timestamps, what exactly are you showing me? When you say console.log shows the correct value, but fit-file-reader shows the wrong ones, what exactly are you console.logging? Are those the inputs?

**Comment by RafaelCENG** [comment] 2024-08-21 17:00
> For the timestamps, what exactly are you showing me? When you say console.log shows the correct value, but fit-file-reader shows the wrong ones, what exactly are you console.logging? Are those the inputs?

Yes they are the inputs i use in the records.

**Comment by RafaelCENG** [comment] 2024-08-21 17:03
```js
		// Aeroscore Session
		const aeroscoreFieldNum = 0;
		fitWriter.writeMessage(
			"field_description",
			{
				developer_data_index: 0,
				field_definition_number: aeroscoreFieldNum,
				field_name: "aeroscore",
				fit_base_type_id: 137, // float64
			},
			null,
			true,
		);

		// Body Angle Record
		const bodyAngleFieldNum = 1;
		fitWriter.writeMessage(
			"field_description",
			{
				developer_data_index: 0,
				field_definition_number: bodyAngleFieldNum,
				field_name: "body_angle",
				fit_base_type_id: 137, // float64
				units: "degrees",
			},
			null,
			true,
		);

		const sessionDevInfo: FitDevInfo[] =
			session.aero_score != null
				? [
						{
							field_num: aeroscoreFieldNum,
							value: session.aero_score,
						} as const,
					]
				: [];

		fitWriter.writeMessage(
			"session",
			{
				event: "session",
				event_type: "stop",
				avg_cadence: session.average_cadence,
				avg_heart_rate: session.average_heart_rate,
				left_right_balance: {
					value: session.average_pedal_balance_left,
				},
				avg_power: session.average_power,
				avg_speed: session.average_speed,
				sport: "cycling",
				start_time: fitWriter.time(new Date()),
				total_ascent: session.elevation_gain,
				total_descent: session.elevation_loss,
				max_heart_rate: session.max_heartrate,
				max_power: session.max_power,
				max_speed: session.max_speed,
				max_cadence: session.max_cadence,
				avg_temperature: session.temperature,
				total_distance: session.total_distance,
				total_timer_time: session.total_time,
				total_calories: session.calories,
				intensity_factor: session.intensity_factor,
				normalized_power: session.normalized_power,
				training_stress_score: session.tss,
			},
			sessionDevInfo,
		);

		for (const metric of metrics) {
			const timestampDate = new Date(metric.timestamp);
			const timestamp = Number(
				fitWriter.time(timestampDate).toString().split(".")[0],
			);
			const position_long = fitWriter.latlng(metric.longitude);
			const position_lat = fitWriter.latlng(metric.latitude);
			const cadence = metric.cadence;
			const distance = metric.distance;
			const power = metric.bike_power;
			const temperature = metric.temperature;
			const speed = metric.speed;
			const heart_rate = metric.heart_rate;
			console.log({ timestamp });

			const recordDevInfo: FitDevInfo[] =
				metric.torso_degrees != null
					? [
							{
								field_num: bodyAngleFieldNum,
								value: metric.torso_degrees,
							} as const,
						]
					: [];

			fitWriter.writeMessage(
				"record",
				{
					timestamp,
					position_long,
					position_lat,
					cadence,
					distance,
					power,
					temperature,
					speed,
					heart_rate,
				},
				recordDevInfo,
			);
		}

**Comment by markw65** [comment] 2024-08-21 18:31
In that code you're only adding one of the fields. You just need to add the other one to the same array.

Not sure what's going on with the timestamps. Away from home right now. I'll take a look tomorrow.

**Comment by RafaelCENG** [comment] 2024-08-21 19:16
> In that code you're only adding one of the fields. You just need to add the other one to the same array.
> 
> Not sure what's going on with the timestamps. Away from home right now. I'll take a look tomorrow.

I want to add multiple extra fields on my record (which is a row every second) and multiple extra fields to my session ( where we have one row with overall data)

**Comment by RafaelCENG** [comment] 2024-08-22 06:36
Multiple fields are working. Now the only thing I have to fix are the timestamps

**Comment by markw65** [comment] 2024-08-22 21:52
Closing this out in favor of #4

**Comment by markw65** [comment] 2024-08-22 21:53
I'm pretty sure the timestamps are correct, and the problem is that fit-file-parser, and fit-file-viewer both have bugs and report the values incorrectly (I think it's likely that fit-file-viewer uses fit-file-parser to read the fit files).

I think the generated files are correct because if I upload them to Garmin Connect, and then export them as .tcx files, the time stamps in the .tcx files are correct, even though fit-file-parser and fit-file-viewer both report incorrect times.

I also have a bug in my tests. I use fit-file-parser to parse the generated fit-files, and then I check that the results match the input file. But fit-file-parser ends up with null timestamps, and a bug in my test code converts that to a `NaN`, and then a carelessly written test passes because `Math.abs(expected - actual) > 1000` is always false when `actual` is `NaN`. I should have been checking `!(Math.abs(expected - actual) <= 1000)` instead, and I would have caught the problem.

The problem is that fit-file-parser basically doesn't handle compressed time stamps in fit files (see the description under [Record Format](https://developer.garmin.com/fit/protocol/#recordformat)).

In fact, looking at the source code, I found [this TODO](https://github.com/jimmykane/fit-parser/blob/61ef7bfb68801a021c1f83b5429e325f8d0883d3/src/binary.js#L325).

But what I also realized was that garmin devices don't seem to generate compressed time stamps; and in fact I found [this reply](https://forums.garmin.com/developer/fit-sdk/f/discussion/311107/compressed-timestamp-header-still-being-used/1507834#1507834) to a question on the Garmin FIT Sdk forum saying that its pretty much dead, and that several third party libraries don't support them.

So I think I need to add an option to disable compressed time stamps, so that third party libraries that don't support them can read the files...

**Closed as completed by markw65** 2024-08-22 21:52 UTC

**Comment by RafaelCENG** [comment] 2024-08-23 06:29
Thanks once again for the reply. We have postponed the fit file creation for now, but I will return.

**Comment by markw65** [comment] 2024-08-23 13:38
FYI that 1.2.0, released yesterday turns off timestamp compression by default, which should fix your timestamp problem.

**Comment by RafaelCENG** [comment] 2024-08-27 06:25
Works perfectly!

**Comment by RafaelCENG** [comment] 2024-08-27 08:23
Managed to import the fit file to Garmin Connect too. By using the fit CSV tool I found also what I was missing. The only thing I do now see in Garmin Connect is the custom fields. Any ideas about that one?

**Comment by markw65** [comment] 2024-08-31 00:46
> The only thing I do now see in Garmin Connect is the custom fields. Any ideas about that one

I believe that Garmin Connect will only show these fields if there's an App in the store that produces the field, and you use it's application_id in you developer_id definition.

I think you also have to make sure that the "device_info" in your generated fit file is one of the devices supported by the App.

Finally, I'm not 100% sure, but I think you have to use the same field numbers as the App uses in the field_description. ie you can't just choose those field numbers randomly, you have to use what the App used. If you're not the App's developer, its probably not easy to figure out what they should be...

**Comment by RafaelCENG** [comment] 2024-08-31 07:47
Thanks I will check it out. I'm in contact with the developer, I already used the correct application_id and field numbers but i will check the rest too.
